version: '3'

services:
  scraper:
    build: .
    image: eitaa-scraper
    environment:
      - EITAA_USERNAME=${EITAA_USERNAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - OUTPUT=/app/output/posts.json
      - SENT_IDS_FILE=/app/sent_ids/sent_ids.json
      - CRON_SCHEDULE=*/5 * * * *
    volumes:
      - ./output:/app/output
      - ./sent_ids:/app/sent_ids
